import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlin: String = "1.4.10"

    const val org_jetbrains_dokka: String = "1.4.10.2"

    const val com_diffplug_gradle_spotless_gradle_plugin: String = "5.7.0"

    const val io_gitlab_arturbosch_detekt_gradle_plugin: String = "1.14.2"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String = "1.4.10"

    const val nebula_nebula_bintray_gradle_plugin: String = "8.5.0"

    const val nebula_maven_publish_gradle_plugin: String = "17.3.2"

    const val nebula_project_gradle_plugin: String = "7.0.9"

    const val nebula_release_gradle_plugin: String = "15.3.0"

    const val worldguard_bukkit: String = "7.0.4"

    const val worldguard_legacy: String = "6.2"

    const val junit_jupiter: String = "5.7.0"

    const val mockito_core: String = "3.6.0"

    const val spigot_api: String = "1.16.4-R0.1-SNAPSHOT"

    const val junit_bom: String = "5.7.0"

    const val mockk: String = "1.10.2"

    const val truth: String = "1.1"

    /**
     * Current version: "6.7"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.7"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
